const institutionTypeData = [
  {
      children:[
          {
              code:"01",
              level:"2",
              name:"农业",
              node:"1",
              onCode:"A"
          },
          {
              code:"02",
              level:"2",
              name:"林业",
              node:"1",
              onCode:"A"
          },
          {
              code:"03",
              level:"2",
              name:"畜牧业",
              node:"1",
              onCode:"A"
          },
          {
              code:"04",
              level:"2",
              name:"渔业",
              node:"1",
              onCode:"A"
          },
          {
              code:"05",
              level:"2",
              name:"农、林、牧、渔专业及辅助性活动",
              node:"1",
              onCode:"A"
          }
      ],
      code:"A",
      level:"1",
      name:"农、林、牧、渔业",
      node:"0",
      
  },
  {
      children:[
          {
              code:"06",
              level:"2",
              name:"煤炭开采和洗选业",
              node:"1",
              onCode:"B"
          },
          {
              code:"07",
              level:"2",
              name:"石油和天然气开采业",
              node:"1",
              onCode:"B"
          },
          {
              code:"08",
              level:"2",
              name:"黑色金属矿采选业",
              node:"1",
              onCode:"B"
          },
          {
              code:"09",
              level:"2",
              name:"有色金属矿采选业",
              node:"1",
              onCode:"B"
          },
          {
              code:"10",
              level:"2",
              name:"非金属矿采选业",
              node:"1",
              onCode:"B"
          },
          {
              code:"11",
              level:"2",
              name:"开采专业及辅助性活动",
              node:"1",
              onCode:"B"
          },
          {
              code:"12",
              level:"2",
              name:"其他采矿业",
              node:"1",
              onCode:"B"
          }
      ],
      code:"B",
      level:"1",
      name:"采矿业",
      node:"0",
      
  },
  {
      children:[
          {
              code:"13",
              level:"2",
              name:"农副食品加工业",
              node:"1",
              onCode:"C"
          },
          {
              code:"14",
              level:"2",
              name:"食品制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"15",
              level:"2",
              name:"酒、饮料和精制茶制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"16",
              level:"2",
              name:"烟草制品业",
              node:"1",
              onCode:"C"
          },
          {
              code:"17",
              level:"2",
              name:"纺织业",
              node:"1",
              onCode:"C"
          },
          {
              code:"18",
              level:"2",
              name:"纺织服装、服饰业",
              node:"1",
              onCode:"C"
          },
          {
              code:"19",
              level:"2",
              name:"皮革、毛皮、羽毛及其制品和制鞋业",
              node:"1",
              onCode:"C"
          },
          {
              code:"20",
              level:"2",
              name:"木材加工和木、竹、藤、棕、草制品业",
              node:"1",
              onCode:"C"
          },
          {
              code:"21",
              level:"2",
              name:"家具制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"22",
              level:"2",
              name:"造纸和纸制品业",
              node:"1",
              onCode:"C"
          },
          {
              code:"23",
              level:"2",
              name:"印刷和记录媒介复制业",
              node:"1",
              onCode:"C"
          },
          {
              code:"24",
              level:"2",
              name:"文教、工美、体育和娱乐用品制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"25",
              level:"2",
              name:"石油、煤炭及其他燃料加工业",
              node:"1",
              onCode:"C"
          },
          {
              code:"26",
              level:"2",
              name:"化学原料和化学制品制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"27",
              level:"2",
              name:"医药制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"28",
              level:"2",
              name:"化学纤维制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"29",
              level:"2",
              name:"橡胶和塑料制品业",
              node:"1",
              onCode:"C"
          },
          {
              code:"30",
              level:"2",
              name:"非金属矿物制品业",
              node:"1",
              onCode:"C"
          },
          {
              code:"31",
              level:"2",
              name:"黑色金属冶炼和压延加工业",
              node:"1",
              onCode:"C"
          },
          {
              code:"32",
              level:"2",
              name:"有色金属冶炼和压延加工业",
              node:"1",
              onCode:"C"
          },
          {
              code:"33",
              level:"2",
              name:"金属制品业",
              node:"1",
              onCode:"C"
          },
          {
              code:"34",
              level:"2",
              name:"通用设备制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"35",
              level:"2",
              name:"专用设备制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"36",
              level:"2",
              name:"汽车制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"37",
              level:"2",
              name:"铁路、船舶、航空航天和其他运输设备制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"38",
              level:"2",
              name:"电气机械和器材制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"39",
              level:"2",
              name:"计算机、通信和其他电子设备制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"40",
              level:"2",
              name:"仪器仪表制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"41",
              level:"2",
              name:"其他制造业",
              node:"1",
              onCode:"C"
          },
          {
              code:"42",
              level:"2",
              name:"废弃资源综合利用业",
              node:"1",
              onCode:"C"
          },
          {
              code:"43",
              level:"2",
              name:"金属制品、机械和设备修理业",
              node:"1",
              onCode:"C"
          }
      ],
      code:"C",
      level:"1",
      name:"制造业",
      node:"0",
      
  },
  {
      children:[
          {
              code:"44",
              level:"2",
              name:"电力、热力生产和供应业",
              node:"1",
              onCode:"D"
          },
          {
              code:"45",
              level:"2",
              name:"燃气生产和供应业",
              node:"1",
              onCode:"D"
          },
          {
              code:"46",
              level:"2",
              name:"水的生产和供应业",
              node:"1",
              onCode:"D"
          }
      ],
      code:"D",
      level:"1",
      name:"电力、热力、燃气及水生产和供应业",
      node:"0",
      
  },
  {
      children:[
          {
              code:"47",
              level:"2",
              name:"房屋建筑业",
              node:"1",
              onCode:"E"
          },
          {
              code:"48",
              level:"2",
              name:"土木工程建筑业",
              node:"1",
              onCode:"E"
          },
          {
              code:"49",
              level:"2",
              name:"建筑安装业",
              node:"1",
              onCode:"E"
          },
          {
              code:"50",
              level:"2",
              name:"建筑装饰、装修和其他建筑业",
              node:"1",
              onCode:"E"
          }
      ],
      code:"E",
      level:"1",
      name:"建筑业",
      node:"0",
      
  },
  {
      children:[
          {
              code:"51",
              level:"2",
              name:"批发业",
              node:"1",
              onCode:"F"
          },
          {
              code:"52",
              level:"2",
              name:"零售业",
              node:"1",
              onCode:"F"
          }
      ],
      code:"F",
      level:"1",
      name:"批发和零售业",
      node:"0",
      
  },
  {
      children:[
          {
              code:"53",
              level:"2",
              name:"铁路运输业",
              node:"1",
              onCode:"G"
          },
          {
              code:"54",
              level:"2",
              name:"道路运输业",
              node:"1",
              onCode:"G"
          },
          {
              code:"55",
              level:"2",
              name:"水上运输业",
              node:"1",
              onCode:"G"
          },
          {
              code:"56",
              level:"2",
              name:"航空运输业",
              node:"1",
              onCode:"G"
          },
          {
              code:"57",
              level:"2",
              name:"管道运输业",
              node:"1",
              onCode:"G"
          },
          {
              code:"58",
              level:"2",
              name:"多式联运和运输代理业",
              node:"1",
              onCode:"G"
          },
          {
              code:"59",
              level:"2",
              name:"仓储业",
              node:"1",
              onCode:"G"
          },
          {
              code:"60",
              level:"2",
              name:"邮政业",
              node:"1",
              onCode:"G"
          }
      ],
      code:"G",
      level:"1",
      name:"交通运输、仓储和邮政业",
      node:"0",
      
  },
  {
      children:[
          {
              code:"61",
              level:"2",
              name:"住宿业",
              node:"1",
              onCode:"H"
          },
          {
              code:"62",
              level:"2",
              name:"餐饮业",
              node:"1",
              onCode:"H"
          }
      ],
      code:"H",
      level:"1",
      name:"住宿和餐饮业",
      node:"0",
      
  },
  {
      children:[
          {
              code:"63",
              level:"2",
              name:"电信、广播电视和卫星传输服务",
              node:"1",
              onCode:"I"
          },
          {
              code:"64",
              level:"2",
              name:"互联网和相关服务",
              node:"1",
              onCode:"I"
          },
          {
              code:"65",
              level:"2",
              name:"软件和信息技术服务业",
              node:"1",
              onCode:"I"
          }
      ],
      code:"I",
      level:"1",
      name:"信息传输、软件和信息技术服务业",
      node:"0",
      
  },
  {
      children:[
          {
              code:"66",
              level:"2",
              name:"货币金融服务",
              node:"1",
              onCode:"J"
          },
          {
              code:"67",
              level:"2",
              name:"资本市场服务",
              node:"1",
              onCode:"J"
          },
          {
              code:"68",
              level:"2",
              name:"保险业",
              node:"1",
              onCode:"J"
          },
          {
              code:"69",
              level:"2",
              name:"其他金融业",
              node:"1",
              onCode:"J"
          }
      ],
      code:"J",
      level:"1",
      name:"金融业",
      node:"0",
      
  },
  {
      code:"K",
      level:"1",
      name:"房地产业",
      node:"1",
      
  },
  {
      children:[
          {
              code:"71",
              level:"2",
              name:"租赁业",
              node:"1",
              onCode:"L"
          },
          {
              code:"72",
              level:"2",
              name:"商务服务业",
              node:"1",
              onCode:"L"
          }
      ],
      code:"L",
      level:"1",
      name:"租赁和商务服务业",
      node:"0",
      
  },
  {
      children:[
          {
              children:[
                  {
                      
                      code:"731",
                      level:"3",
                      name:"自然科学研究和试验发展",
                      node:"1",
                      onCode:"73"
                  },
                  {
                      
                      code:"732",
                      level:"3",
                      name:"工程和技术研究和试验发展",
                      node:"1",
                      onCode:"73"
                  },
                  {
                      
                      code:"733",
                      level:"3",
                      name:"农业科学研究和试验发展",
                      node:"1",
                      onCode:"73"
                  },
                  {
                      
                      code:"734",
                      level:"3",
                      name:"医学研究和试验发展",
                      node:"1",
                      onCode:"73"
                  },
                  {
                      
                      code:"735",
                      level:"3",
                      name:"社会人文科学研究",
                      node:"1",
                      onCode:"73"
                  }
              ],
              code:"73",
              level:"2",
              name:"研究和试验发展",
              node:"0",
              onCode:"M"
          },
          {
              children:[
                  {
                      
                      code:"741",
                      level:"3",
                      name:"气象服务",
                      node:"1",
                      onCode:"74"
                  },
                  {
                      
                      code:"742",
                      level:"3",
                      name:"地震服务",
                      node:"1",
                      onCode:"74"
                  },
                  {
                      children:[
                          {
                              code:"7431",
                              level:"4",
                              name:"海洋气象服务",
                              node:"1",
                              onCode:"743"
                          },
                          {
                              code:"7432",
                              level:"4",
                              name:"海洋环境服务",
                              node:"1",
                              onCode:"743"
                          },
                          {
                              code:"7439",
                              level:"4",
                              name:"其他海洋服务",
                              node:"1",
                              onCode:"743"
                          }
                      ],
                      code:"743",
                      level:"3",
                      name:"海洋服务",
                      node:"0",
                      onCode:"74"
                  },
                  {
                      children:[
                          {
                              code:"7441",
                              level:"4",
                              name:"遥感测绘服务",
                              node:"1",
                              onCode:"744"
                          },
                          {
                              code:"7449",
                              level:"4",
                              name:"其他测绘地理信息服务",
                              node:"1",
                              onCode:"744"
                          }
                      ],
                      code:"744",
                      level:"3",
                      name:"测绘地理信息服务",
                      node:"0",
                      onCode:"74"
                  },
                  {
                      children:[
                          {
                              code:"7451",
                              level:"4",
                              name:"检验检疫服务",
                              node:"1",
                              onCode:"745"
                          },
                          {
                              code:"7452",
                              level:"4",
                              name:"检测服务",
                              node:"1",
                              onCode:"745"
                          },
                          {
                              code:"7453",
                              level:"4",
                              name:"计量服务",
                              node:"1",
                              onCode:"745"
                          },
                          {
                              code:"7454",
                              level:"4",
                              name:"标准化服务",
                              node:"1",
                              onCode:"745"
                          },
                          {
                              code:"7455",
                              level:"4",
                              name:"认证认可服务",
                              node:"1",
                              onCode:"745"
                          },
                          {
                              code:"7459",
                              level:"4",
                              name:"其他质检技术服务",
                              node:"1",
                              onCode:"745"
                          }
                      ],
                      code:"745",
                      level:"3",
                      name:"质检技术服务",
                      node:"0",
                      onCode:"74"
                  },
                  {
                      children:[
                          {
                              code:"7461",
                              level:"4",
                              name:"环境保护监测",
                              node:"1",
                              onCode:"746"
                          },
                          {
                              code:"7462",
                              level:"4",
                              name:"生态资源监测",
                              node:"1",
                              onCode:"746"
                          },
                          {
                              code:"7463",
                              level:"4",
                              name:"野生动物疫源疫病防控监测",
                              node:"1",
                              onCode:"746"
                          }
                      ],
                      code:"746",
                      level:"3",
                      name:"环境与生态监测检测服务",
                      node:"0",
                      onCode:"74"
                  },
                  {
                      children:[
                          {
                              code:"7471",
                              level:"4",
                              name:"能源矿产地质勘查",
                              node:"1",
                              onCode:"747"
                          },
                          {
                              code:"7472",
                              level:"4",
                              name:"固体矿产地质勘查",
                              node:"1",
                              onCode:"747"
                          },
                          {
                              code:"7473",
                              level:"4",
                              name:"水、二氧化碳等矿产地质勘查",
                              node:"1",
                              onCode:"747"
                          },
                          {
                              code:"7474",
                              level:"4",
                              name:"基础地质勘查",
                              node:"1",
                              onCode:"747"
                          },
                          {
                              code:"7475",
                              level:"4",
                              name:"地质勘查技术服务",
                              node:"1",
                              onCode:"747"
                          }
                      ],
                      code:"747",
                      level:"3",
                      name:"地质勘查",
                      node:"0",
                      onCode:"74"
                  },
                  {
                      children:[
                          {
                              code:"7481",
                              level:"4",
                              name:"工程管理服务",
                              node:"1",
                              onCode:"748"
                          },
                          {
                              code:"7482",
                              level:"4",
                              name:"工程监理服务",
                              node:"1",
                              onCode:"748"
                          },
                          {
                              code:"7483",
                              level:"4",
                              name:"工程勘察活动",
                              node:"1",
                              onCode:"748"
                          },
                          {
                              code:"7484",
                              level:"4",
                              name:"工程设计活动",
                              node:"1",
                              onCode:"748"
                          },
                          {
                              code:"7485",
                              level:"4",
                              name:"规划设计管理",
                              node:"1",
                              onCode:"748"
                          },
                          {
                              code:"7486",
                              level:"4",
                              name:"土地规划服务",
                              node:"1",
                              onCode:"748"
                          }
                      ],
                      code:"748",
                      level:"3",
                      name:"工程技术与设计服务",
                      node:"0",
                      onCode:"74"
                  },
                  {
                      children:[
                          {
                              code:"7491",
                              level:"4",
                              name:"工业设计服务",
                              node:"1",
                              onCode:"749"
                          },
                          {
                              code:"7492",
                              level:"4",
                              name:"专业设计服务",
                              node:"1",
                              onCode:"749"
                          },
                          {
                              code:"7493",
                              level:"4",
                              name:"兽医服务",
                              node:"1",
                              onCode:"749"
                          },
                          {
                              code:"7499",
                              level:"4",
                              name:"其他未列明专业技术服务业",
                              node:"1",
                              onCode:"749"
                          }
                      ],
                      code:"749",
                      level:"3",
                      name:"工业与专业设计及其他专业技术服务",
                      node:"0",
                      onCode:"74"
                  }
              ],
              code:"74",
              level:"2",
              name:"专业技术服务业",
              node:"0",
              onCode:"M"
          },
          {
              children:[
                  {
                      children:[
                          {
                              code:"7511",
                              level:"4",
                              name:"农林牧渔技术推广服务",
                              node:"1",
                              onCode:"751"
                          },
                          {
                              code:"7512",
                              level:"4",
                              name:"生物技术推广服务",
                              node:"1",
                              onCode:"751"
                          },
                          {
                              code:"7513",
                              level:"4",
                              name:"新材料技术推广服务",
                              node:"1",
                              onCode:"751"
                          },
                          {
                              code:"7514",
                              level:"4",
                              name:"节能技术推广服务",
                              node:"1",
                              onCode:"751"
                          },
                          {
                              code:"7515",
                              level:"4",
                              name:"新能源技术推广服务",
                              node:"1",
                              onCode:"751"
                          },
                          {
                              code:"7516",
                              level:"4",
                              name:"环保技术推广服务",
                              node:"1",
                              onCode:"751"
                          },
                          {
                              code:"7517",
                              level:"4",
                              name:"三维（3D）打印技术推广服务",
                              node:"1",
                              onCode:"751"
                          },
                          {
                              code:"7519",
                              level:"4",
                              name:"其他技术推广服务",
                              node:"1",
                              onCode:"751"
                          }
                      ],
                      code:"751",
                      level:"3",
                      name:"技术推广服务",
                      node:"0",
                      onCode:"75"
                  },
                  {
                      
                      code:"752",
                      level:"3",
                      name:"知识产权服务",
                      node:"1",
                      onCode:"75"
                  },
                  {
                      
                      code:"753",
                      level:"3",
                      name:"科技中介服务",
                      node:"1",
                      onCode:"75"
                  },
                  {
                      
                      code:"754",
                      level:"3",
                      name:"创业空间服务",
                      node:"1",
                      onCode:"75"
                  },
                  {
                      
                      code:"759",
                      level:"3",
                      name:"其他科技推广服务业",
                      node:"1",
                      onCode:"75"
                  }
              ],
              code:"75",
              level:"2",
              name:"科技推广和应用服务业",
              node:"0",
              onCode:"M"
          }
      ],
      code:"M",
      level:"1",
      name:"科学研究和技术服务业",
      node:"0",
      
  },
  {
      children:[
          {
              children:[
                  {
                      
                      code:"761",
                      level:"3",
                      name:"防洪除涝设施管理",
                      node:"1",
                      onCode:"76"
                  },
                  {
                      
                      code:"762",
                      level:"3",
                      name:"水资源管理",
                      node:"1",
                      onCode:"76"
                  },
                  {
                      
                      code:"763",
                      level:"3",
                      name:"天然水收集与分配",
                      node:"1",
                      onCode:"76"
                  },
                  {
                      
                      code:"764",
                      level:"3",
                      name:"水文服务",
                      node:"1",
                      onCode:"76"
                  },
                  {
                      
                      code:"769",
                      level:"3",
                      name:"其他水利管理业",
                      node:"1",
                      onCode:"76"
                  }
              ],
              code:"76",
              level:"2",
              name:"水利管理业",
              node:"0",
              onCode:"N"
          },
          {
              children:[
                  {
                      children:[
                          {
                              code:"7711",
                              level:"4",
                              name:"自然生态系统保护管理",
                              node:"1",
                              onCode:"771"
                          },
                          {
                              code:"7712",
                              level:"4",
                              name:"自然遗迹保护管理",
                              node:"1",
                              onCode:"771"
                          },
                          {
                              code:"7713",
                              level:"4",
                              name:"野生动物保护",
                              node:"1",
                              onCode:"771"
                          },
                          {
                              code:"7714",
                              level:"4",
                              name:"野生植物保护",
                              node:"1",
                              onCode:"771"
                          },
                          {
                              code:"7715",
                              level:"4",
                              name:"动物园、水族馆管理服务",
                              node:"1",
                              onCode:"771"
                          },
                          {
                              code:"7716",
                              level:"4",
                              name:"植物园管理服务",
                              node:"1",
                              onCode:"771"
                          },
                          {
                              code:"7719",
                              level:"4",
                              name:"其他自然保护",
                              node:"1",
                              onCode:"771"
                          }
                      ],
                      code:"771",
                      level:"3",
                      name:"生态保护",
                      node:"0",
                      onCode:"77"
                  },
                  {
                      children:[
                          {
                              code:"7721",
                              level:"4",
                              name:"水污染治理",
                              node:"1",
                              onCode:"772"
                          },
                          {
                              code:"7722",
                              level:"4",
                              name:"大气污染治理",
                              node:"1",
                              onCode:"772"
                          },
                          {
                              code:"7723",
                              level:"4",
                              name:"固体废物治理",
                              node:"1",
                              onCode:"772"
                          },
                          {
                              code:"7724",
                              level:"4",
                              name:"危险废物治理",
                              node:"1",
                              onCode:"772"
                          },
                          {
                              code:"7725",
                              level:"4",
                              name:"放射性废物治理",
                              node:"1",
                              onCode:"772"
                          },
                          {
                              code:"7726",
                              level:"4",
                              name:"土壤污染治理与修复服务",
                              node:"1",
                              onCode:"772"
                          },
                          {
                              code:"7727",
                              level:"4",
                              name:"噪声与振动控制服务",
                              node:"1",
                              onCode:"772"
                          },
                          {
                              code:"7729",
                              level:"4",
                              name:"其他污染治理",
                              node:"1",
                              onCode:"772"
                          }
                      ],
                      code:"772",
                      level:"3",
                      name:"环境治理业",
                      node:"0",
                      onCode:"77"
                  }
              ],
              code:"77",
              level:"2",
              name:"生态保护和环境治理业",
              node:"0",
              onCode:"N"
          },
          {
              children:[
                  {
                      
                      code:"781",
                      level:"3",
                      name:"市政设施管理",
                      node:"1",
                      onCode:"78"
                  },
                  {
                      
                      code:"782",
                      level:"3",
                      name:"城乡市容管理",
                      node:"1",
                      onCode:"78"
                  },
                  {
                      
                      code:"783",
                      level:"3",
                      name:"绿化管理",
                      node:"1",
                      onCode:"78"
                  },
                  {
                      
                      code:"784",
                      level:"3",
                      name:"城市公园管理",
                      node:"1",
                      onCode:"78"
                  },
                  {
                      children:[
                          {
                              code:"7851",
                              level:"4",
                              name:"名胜风景区管理",
                              node:"1",
                              onCode:"785"
                          },
                          {
                              code:"7852",
                              level:"4",
                              name:"森林公园管理",
                              node:"1",
                              onCode:"785"
                          },
                          {
                              code:"7859",
                              level:"4",
                              name:"其他游览景区管理",
                              node:"1",
                              onCode:"785"
                          }
                      ],
                      code:"785",
                      level:"3",
                      name:"游览景区管理",
                      node:"0",
                      onCode:"78"
                  }
              ],
              code:"78",
              level:"2",
              name:"公共设施管理业",
              node:"0",
              onCode:"N"
          },
          {
              children:[
                  {
                      
                      code:"791",
                      level:"3",
                      name:"土地整治服务",
                      node:"1",
                      onCode:"79"
                  },
                  {
                      
                      code:"792",
                      level:"3",
                      name:"土地调查评估服务",
                      node:"1",
                      onCode:"79"
                  },
                  {
                      
                      code:"793",
                      level:"3",
                      name:"土地登记服务",
                      node:"1",
                      onCode:"79"
                  },
                  {
                      
                      code:"794",
                      level:"3",
                      name:"土地登记代理服务",
                      node:"1",
                      onCode:"79"
                  },
                  {
                      
                      code:"799",
                      level:"3",
                      name:"其他土地管理服务",
                      node:"1",
                      onCode:"79"
                  }
              ],
              code:"79",
              level:"2",
              name:"土地管理业",
              node:"0",
              onCode:"N"
          }
      ],
      code:"N",
      level:"1",
      name:"水利、环境和公共设施管理业",
      node:"0",
      
  },
  {
      children:[
          {
              children:[
                  {
                      
                      code:"801",
                      level:"3",
                      name:"家庭服务",
                      node:"1",
                      onCode:"80"
                  },
                  {
                      
                      code:"802",
                      level:"3",
                      name:"托儿所服务",
                      node:"1",
                      onCode:"80"
                  },
                  {
                      
                      code:"803",
                      level:"3",
                      name:"洗染服务",
                      node:"1",
                      onCode:"80"
                  },
                  {
                      
                      code:"804",
                      level:"3",
                      name:"理发及美容服务",
                      node:"1",
                      onCode:"80"
                  },
                  {
                      children:[
                          {
                              code:"8051",
                              level:"4",
                              name:"洗浴服务",
                              node:"1",
                              onCode:"805"
                          },
                          {
                              code:"8052",
                              level:"4",
                              name:"足浴服务",
                              node:"1",
                              onCode:"805"
                          },
                          {
                              code:"8053",
                              level:"4",
                              name:"养生保健服务",
                              node:"1",
                              onCode:"805"
                          }
                      ],
                      code:"805",
                      level:"3",
                      name:"洗浴和保健养生服务",
                      node:"0",
                      onCode:"80"
                  },
                  {
                      
                      code:"806",
                      level:"3",
                      name:"摄影扩印服务",
                      node:"1",
                      onCode:"80"
                  },
                  {
                      
                      code:"807",
                      level:"3",
                      name:"婚姻服务",
                      node:"1",
                      onCode:"80"
                  },
                  {
                      
                      code:"808",
                      level:"3",
                      name:"殡葬服务",
                      node:"1",
                      onCode:"80"
                  },
                  {
                      
                      code:"809",
                      level:"3",
                      name:"其他居民服务业",
                      node:"1",
                      onCode:"80"
                  }
              ],
              code:"80",
              level:"2",
              name:"居民服务业",
              node:"0",
              onCode:"O"
          },
          {
              children:[

              ],
              code:"81",
              level:"2",
              name:"机动车、电子产品和日用产品修理业",
              node:"1",
              onCode:"O"
          },
          {
              children:[

              ],
              code:"82",
              level:"2",
              name:"其他服务业",
              node:"1",
              onCode:"O"
          }
      ],
      code:"O",
      level:"1",
      name:"居民服务、修理和其他服务业",
      node:"0",
      
  },
  {
      children:[
          {
              children:[
                  {
                      children:[
                          {
                              code:"8310",
                              level:"4",
                              name:"学前教育",
                              node:"1",
                              onCode:"831"
                          }
                      ],
                      code:"831",
                      level:"3",
                      name:"学前教育",
                      node:"0",
                      onCode:"83"
                  },
                  {
                      children:[
                          {
                              code:"8321",
                              level:"4",
                              name:"普通小学教育",
                              node:"1",
                              onCode:"832"
                          },
                          {
                              code:"8322",
                              level:"4",
                              name:"成人小学教育",
                              node:"1",
                              onCode:"832"
                          }
                      ],
                      code:"832",
                      level:"3",
                      name:"初等教育",
                      node:"0",
                      onCode:"83"
                  },
                  {
                      children:[
                          {
                              code:"8331",
                              level:"4",
                              name:"普通初中教育",
                              node:"1",
                              onCode:"833"
                          },
                          {
                              code:"8332",
                              level:"4",
                              name:"职业初中教育",
                              node:"1",
                              onCode:"833"
                          },
                          {
                              code:"8333",
                              level:"4",
                              name:"成人初中教育",
                              node:"1",
                              onCode:"833"
                          },
                          {
                              code:"8334",
                              level:"4",
                              name:"普通高中教育",
                              node:"1",
                              onCode:"833"
                          },
                          {
                              code:"8335",
                              level:"4",
                              name:"成人高中教育",
                              node:"1",
                              onCode:"833"
                          },
                          {
                              code:"8336",
                              level:"4",
                              name:"中等职业学校教育",
                              node:"1",
                              onCode:"833"
                          }
                      ],
                      code:"833",
                      level:"3",
                      name:"中等教育",
                      node:"0",
                      onCode:"83"
                  },
                  {
                      children:[
                          {
                              code:"8341",
                              level:"4",
                              name:"普通高等教育",
                              node:"1",
                              onCode:"834"
                          },
                          {
                              code:"8342",
                              level:"4",
                              name:"成人高等教育",
                              node:"1",
                              onCode:"834"
                          }
                      ],
                      code:"834",
                      level:"3",
                      name:"高等教育",
                      node:"0",
                      onCode:"83"
                  },
                  {
                      children:[
                          {
                              code:"8350",
                              level:"4",
                              name:"特殊教育",
                              node:"1",
                              onCode:"835"
                          }
                      ],
                      code:"835",
                      level:"3",
                      name:"特殊教育",
                      node:"0",
                      onCode:"83"
                  },
                  {
                      children:[
                          {
                              code:"8391",
                              level:"4",
                              name:"职业技能培训",
                              node:"1",
                              onCode:"839"
                          },
                          {
                              code:"8392",
                              level:"4",
                              name:"体校及体育培训",
                              node:"1",
                              onCode:"839"
                          },
                          {
                              code:"8393",
                              level:"4",
                              name:"文化艺术培训",
                              node:"1",
                              onCode:"839"
                          },
                          {
                              code:"8394",
                              level:"4",
                              name:"教育辅助服务",
                              node:"1",
                              onCode:"839"
                          },
                          {
                              code:"8399",
                              level:"4",
                              name:"其他未列明教育",
                              node:"1",
                              onCode:"839"
                          }
                      ],
                      code:"839",
                      level:"3",
                      name:"技能培训、教育辅助及其他教育",
                      node:"0",
                      onCode:"83"
                  }
              ],
              code:"83",
              level:"2",
              name:"教育",
              node:"0",
              onCode:"P"
          }
      ],
      code:"P",
      level:"1",
      name:"教育",
      node:"0",
      
  },
  {
      children:[
          {
              children:[
                  {
                      children:[
                          {
                              code:"8411",
                              level:"4",
                              name:"综合医院",
                              node:"1",
                              onCode:"841"
                          },
                          {
                              code:"8412",
                              level:"4",
                              name:"中医医院",
                              node:"1",
                              onCode:"841"
                          },
                          {
                              code:"8413",
                              level:"4",
                              name:"中西医结合医院",
                              node:"1",
                              onCode:"841"
                          },
                          {
                              code:"8414",
                              level:"4",
                              name:"民族医院",
                              node:"1",
                              onCode:"841"
                          },
                          {
                              code:"8415",
                              level:"4",
                              name:"专科医院",
                              node:"1",
                              onCode:"841"
                          },
                          {
                              code:"8416",
                              level:"4",
                              name:"疗养院",
                              node:"1",
                              onCode:"841"
                          }
                      ],
                      code:"841",
                      level:"3",
                      name:"医院",
                      node:"0",
                      onCode:"84"
                  },
                  {
                      children:[
                          {
                              code:"8421",
                              level:"4",
                              name:"社区卫生服务中心（站）",
                              node:"1",
                              onCode:"842"
                          },
                          {
                              code:"8422",
                              level:"4",
                              name:"街道卫生院",
                              node:"1",
                              onCode:"842"
                          },
                          {
                              code:"8423",
                              level:"4",
                              name:"乡镇卫生院",
                              node:"1",
                              onCode:"842"
                          },
                          {
                              code:"8424",
                              level:"4",
                              name:"村卫生室",
                              node:"1",
                              onCode:"842"
                          },
                          {
                              code:"8425",
                              level:"4",
                              name:"门诊部（所）",
                              node:"1",
                              onCode:"842"
                          }
                      ],
                      code:"842",
                      level:"3",
                      name:"基层医疗卫生服务",
                      node:"0",
                      onCode:"84"
                  },
                  {
                      children:[
                          {
                              code:"8431",
                              level:"4",
                              name:"疾病预防控制中心",
                              node:"1",
                              onCode:"843"
                          },
                          {
                              code:"8432",
                              level:"4",
                              name:"专科疾病防治院（所、站）",
                              node:"1",
                              onCode:"843"
                          },
                          {
                              code:"8433",
                              level:"4",
                              name:"妇幼保健院（所、站）",
                              node:"1",
                              onCode:"843"
                          },
                          {
                              code:"8434",
                              level:"4",
                              name:"急救中心（站）服务",
                              node:"1",
                              onCode:"843"
                          },
                          {
                              code:"8435",
                              level:"4",
                              name:"采供血机构服务",
                              node:"1",
                              onCode:"843"
                          },
                          {
                              code:"8436",
                              level:"4",
                              name:"计划生育技术服务活动",
                              node:"1",
                              onCode:"843"
                          }
                      ],
                      code:"843",
                      level:"3",
                      name:"专业公共卫生服务",
                      node:"0",
                      onCode:"84"
                  },
                  {
                      children:[
                          {
                              code:"8491",
                              level:"4",
                              name:"健康体检服务",
                              node:"1",
                              onCode:"849"
                          },
                          {
                              code:"8492",
                              level:"4",
                              name:"临床检验服务",
                              node:"1",
                              onCode:"849"
                          },
                          {
                              code:"8499",
                              level:"4",
                              name:"其他未列明卫生服务",
                              node:"1",
                              onCode:"849"
                          }
                      ],
                      code:"849",
                      level:"3",
                      name:"其他卫生活动",
                      node:"0",
                      onCode:"84"
                  }
              ],
              code:"84",
              level:"2",
              name:"卫生",
              node:"0",
              onCode:"Q"
          },
          {
              children:[
                  {
                      children:[
                          {
                              code:"8511",
                              level:"4",
                              name:"干部休养所",
                              node:"1",
                              onCode:"851"
                          },
                          {
                              code:"8512",
                              level:"4",
                              name:"护理机构服务",
                              node:"1",
                              onCode:"851"
                          },
                          {
                              code:"8513",
                              level:"4",
                              name:"精神康复服务",
                              node:"1",
                              onCode:"851"
                          },
                          {
                              code:"8514",
                              level:"4",
                              name:"老年人、残疾人养护服务",
                              node:"1",
                              onCode:"851"
                          },
                          {
                              code:"8515",
                              level:"4",
                              name:"临终关怀服务",
                              node:"1",
                              onCode:"851"
                          },
                          {
                              code:"8516",
                              level:"4",
                              name:"孤残儿童收养和庇护服务",
                              node:"1",
                              onCode:"851"
                          },
                          {
                              code:"8519",
                              level:"4",
                              name:"其他提供住宿社会救助",
                              node:"1",
                              onCode:"851"
                          }
                      ],
                      code:"851",
                      level:"3",
                      name:"提供住宿社会工作",
                      node:"0",
                      onCode:"85"
                  },
                  {
                      children:[
                          {
                              code:"8521",
                              level:"4",
                              name:"社会看护与帮助服务",
                              node:"1",
                              onCode:"852"
                          },
                          {
                              code:"8522",
                              level:"4",
                              name:"康复辅具适配服务",
                              node:"1",
                              onCode:"852"
                          },
                          {
                              code:"8529",
                              level:"4",
                              name:"其他不提供住宿社会工作",
                              node:"1",
                              onCode:"852"
                          }
                      ],
                      code:"852",
                      level:"3",
                      name:"不提供住宿社会工作",
                      node:"0",
                      onCode:"85"
                  }
              ],
              code:"85",
              level:"2",
              name:"社会工作",
              node:"0",
              onCode:"Q"
          }
      ],
      code:"Q",
      level:"1",
      name:"卫生和社会工作",
      node:"0",
      
  },
  {
      children:[
          {
              children:[
                  {
                      
                      code:"861",
                      level:"3",
                      name:"新闻业",
                      node:"1",
                      onCode:"86"
                  },
                  {
                      children:[
                          {
                              code:"8621",
                              level:"4",
                              name:"图书出版",
                              node:"1",
                              onCode:"862"
                          },
                          {
                              code:"8622",
                              level:"4",
                              name:"报纸出版",
                              node:"1",
                              onCode:"862"
                          },
                          {
                              code:"8623",
                              level:"4",
                              name:"期刊出版",
                              node:"1",
                              onCode:"862"
                          },
                          {
                              code:"8624",
                              level:"4",
                              name:"音像制品出版",
                              node:"1",
                              onCode:"862"
                          },
                          {
                              code:"8625",
                              level:"4",
                              name:"电子出版物出版",
                              node:"1",
                              onCode:"862"
                          },
                          {
                              code:"8626",
                              level:"4",
                              name:"数字出版",
                              node:"1",
                              onCode:"862"
                          },
                          {
                              code:"8629",
                              level:"4",
                              name:"其他出版业",
                              node:"1",
                              onCode:"862"
                          }
                      ],
                      code:"862",
                      level:"3",
                      name:"出版业",
                      node:"0",
                      onCode:"86"
                  }
              ],
              code:"86",
              level:"2",
              name:"新闻和出版业",
              node:"0",
              onCode:"R"
          },
          {
              children:[
                  {
                      
                      code:"871",
                      level:"3",
                      name:"广播",
                      node:"1",
                      onCode:"87"
                  },
                  {
                      
                      code:"872",
                      level:"3",
                      name:"电视",
                      node:"1",
                      onCode:"87"
                  },
                  {
                      
                      code:"873",
                      level:"3",
                      name:"影视节目制作",
                      node:"1",
                      onCode:"87"
                  },
                  {
                      
                      code:"874",
                      level:"3",
                      name:"广播电视集成播控",
                      node:"1",
                      onCode:"87"
                  },
                  {
                      
                      code:"875",
                      level:"3",
                      name:"电影和广播电视节目发行",
                      node:"1",
                      onCode:"87"
                  },
                  {
                      
                      code:"876",
                      level:"3",
                      name:"电影放映",
                      node:"1",
                      onCode:"87"
                  },
                  {
                      
                      code:"877",
                      level:"3",
                      name:"录音制作",
                      node:"1",
                      onCode:"87"
                  }
              ],
              code:"87",
              level:"2",
              name:"广播、电视、电影和录音制作业",
              node:"0",
              onCode:"R"
          },
          {
              children:[
                  {
                      
                      code:"881",
                      level:"3",
                      name:"文艺创作与表演",
                      node:"1",
                      onCode:"88"
                  },
                  {
                      
                      code:"882",
                      level:"3",
                      name:"艺术表演场馆",
                      node:"1",
                      onCode:"88"
                  },
                  {
                      children:[
                          {
                              code:"8831",
                              level:"4",
                              name:"图书馆",
                              node:"1",
                              onCode:"883"
                          },
                          {
                              code:"8832",
                              level:"4",
                              name:"档案馆",
                              node:"1",
                              onCode:"883"
                          }
                      ],
                      code:"883",
                      level:"3",
                      name:"图书馆与档案馆",
                      node:"0",
                      onCode:"88"
                  },
                  {
                      
                      code:"884",
                      level:"3",
                      name:"文物及非物质文化遗产保护",
                      node:"1",
                      onCode:"88"
                  },
                  {
                      
                      code:"885",
                      level:"3",
                      name:"博物馆",
                      node:"1",
                      onCode:"88"
                  },
                  {
                      
                      code:"886",
                      level:"3",
                      name:"烈士陵园、纪念馆",
                      node:"1",
                      onCode:"88"
                  },
                  {
                      
                      code:"887",
                      level:"3",
                      name:"群众文化活动",
                      node:"1",
                      onCode:"88"
                  },
                  {
                      
                      code:"889",
                      level:"3",
                      name:"其他文化艺术业",
                      node:"1",
                      onCode:"88"
                  }
              ],
              code:"88",
              level:"2",
              name:"文化艺术业",
              node:"0",
              onCode:"R"
          },
          {
              children:[
                  {
                      children:[
                          {
                              code:"8911",
                              level:"4",
                              name:"体育竞赛组织",
                              node:"1",
                              onCode:"891"
                          },
                          {
                              code:"8912",
                              level:"4",
                              name:"体育保障组织",
                              node:"1",
                              onCode:"891"
                          },
                          {
                              code:"8919",
                              level:"4",
                              name:"其他体育组织",
                              node:"1",
                              onCode:"891"
                          }
                      ],
                      code:"891",
                      level:"3",
                      name:"体育组织",
                      node:"0",
                      onCode:"89"
                  },
                  {
                      children:[
                          {
                              code:"8921",
                              level:"4",
                              name:"体育场馆管理",
                              node:"1",
                              onCode:"892"
                          },
                          {
                              code:"8929",
                              level:"4",
                              name:"其他体育场地设施管理",
                              node:"1",
                              onCode:"892"
                          }
                      ],
                      code:"892",
                      level:"3",
                      name:"体育场地设施管理",
                      node:"0",
                      onCode:"89"
                  },
                  {
                      children:[
                          {
                              code:"8930",
                              level:"4",
                              name:"休闲健身活动",
                              node:"1",
                              onCode:"893"
                          }
                      ],
                      code:"893",
                      level:"3",
                      name:"休闲健身活动",
                      node:"0",
                      onCode:"89"
                  },
                  {
                      children:[
                          {
                              code:"8991",
                              level:"4",
                              name:"体育中介代理服务",
                              node:"1",
                              onCode:"899"
                          },
                          {
                              code:"8992",
                              level:"4",
                              name:"体育健康服务",
                              node:"1",
                              onCode:"899"
                          },
                          {
                              code:"8999",
                              level:"4",
                              name:"其他未列明体育",
                              node:"1",
                              onCode:"899"
                          }
                      ],
                      code:"899",
                      level:"3",
                      name:"其他体育",
                      node:"0",
                      onCode:"89"
                  }
              ],
              code:"89",
              level:"2",
              name:"体育",
              node:"0",
              onCode:"R"
          },
          {
              children:[
                  {
                      children:[
                          {
                              code:"9011",
                              level:"4",
                              name:"歌舞厅娱乐活动",
                              node:"1",
                              onCode:"901"
                          },
                          {
                              code:"9012",
                              level:"4",
                              name:"电子游艺厅娱乐活动",
                              node:"1",
                              onCode:"901"
                          },
                          {
                              code:"9013",
                              level:"4",
                              name:"网吧活动",
                              node:"1",
                              onCode:"901"
                          },
                          {
                              code:"9019",
                              level:"4",
                              name:"其他室内娱乐活动",
                              node:"1",
                              onCode:"901"
                          }
                      ],
                      code:"901",
                      level:"3",
                      name:"室内娱乐活动",
                      node:"0",
                      onCode:"90"
                  },
                  {
                      
                      code:"902",
                      level:"3",
                      name:"游乐园",
                      node:"1",
                      onCode:"90"
                  },
                  {
                      
                      code:"903",
                      level:"3",
                      name:"休闲观光活动",
                      node:"1",
                      onCode:"90"
                  },
                  {
                      children:[
                          {
                              code:"9041",
                              level:"4",
                              name:"体育彩票服务",
                              node:"1",
                              onCode:"904"
                          },
                          {
                              code:"9042",
                              level:"4",
                              name:"福利彩票服务",
                              node:"1",
                              onCode:"904"
                          },
                          {
                              code:"9049",
                              level:"4",
                              name:"其他彩票服务",
                              node:"1",
                              onCode:"904"
                          }
                      ],
                      code:"904",
                      level:"3",
                      name:"彩票活动",
                      node:"0",
                      onCode:"90"
                  },
                  {
                      children:[
                          {
                              code:"9051",
                              level:"4",
                              name:"文化活动服务",
                              node:"1",
                              onCode:"905"
                          },
                          {
                              code:"9052",
                              level:"4",
                              name:"体育表演服务",
                              node:"1",
                              onCode:"905"
                          },
                          {
                              code:"9053",
                              level:"4",
                              name:"文化娱乐经纪人",
                              node:"1",
                              onCode:"905"
                          },
                          {
                              code:"9054",
                              level:"4",
                              name:"体育经纪人",
                              node:"1",
                              onCode:"905"
                          },
                          {
                              code:"9059",
                              level:"4",
                              name:"其他文化艺术经纪代理",
                              node:"1",
                              onCode:"905"
                          }
                      ],
                      code:"905",
                      level:"3",
                      name:"文化体育娱乐活动与经纪代理服务",
                      node:"0",
                      onCode:"90"
                  },
                  {
                      children:[
                          {
                              code:"9090",
                              level:"4",
                              name:"其他娱乐业",
                              node:"1",
                              onCode:"909"
                          }
                      ],
                      code:"909",
                      level:"3",
                      name:"其他娱乐业",
                      node:"0",
                      onCode:"90"
                  }
              ],
              code:"90",
              level:"2",
              name:"娱乐业",
              node:"0",
              onCode:"R"
          }
      ],
      code:"R",
      level:"1",
      name:"文化、体育和娱乐业",
      node:"0",
      
  },
  {
      children:[
          {
              children:[
                  {
                      children:[
                          {
                              code:"9100",
                              level:"4",
                              name:"中国共产党机关",
                              node:"1",
                              onCode:"910"
                          }
                      ],
                      code:"910",
                      level:"3",
                      name:"中国共产党机关",
                      node:"0",
                      onCode:"91"
                  }
              ],
              code:"91",
              level:"2",
              name:"中国共产党机关",
              node:"0",
              onCode:"S"
          },
          {
              children:[
                  {
                      children:[
                          {
                              code:"9210",
                              level:"4",
                              name:"国家权力机构",
                              node:"1",
                              onCode:"921"
                          }
                      ],
                      code:"921",
                      level:"3",
                      name:"国家权力机构",
                      node:"0",
                      onCode:"92"
                  },
                  {
                      children:[
                          {
                              code:"9221",
                              level:"4",
                              name:"综合事务管理机构",
                              node:"1",
                              onCode:"922"
                          },
                          {
                              code:"9222",
                              level:"4",
                              name:"对外事务管理机构",
                              node:"1",
                              onCode:"922"
                          },
                          {
                              code:"9223",
                              level:"4",
                              name:"公共安全管理机构",
                              node:"1",
                              onCode:"922"
                          },
                          {
                              code:"9224",
                              level:"4",
                              name:"社会事务管理机构",
                              node:"1",
                              onCode:"922"
                          },
                          {
                              code:"9225",
                              level:"4",
                              name:"经济事务管理机构",
                              node:"1",
                              onCode:"922"
                          },
                          {
                              code:"9226",
                              level:"4",
                              name:"行政监督检查机构",
                              node:"1",
                              onCode:"922"
                          }
                      ],
                      code:"922",
                      level:"3",
                      name:"国家行政机构",
                      node:"0",
                      onCode:"92"
                  },
                  {
                      children:[
                          {
                              code:"9231",
                              level:"4",
                              name:"人民法院",
                              node:"1",
                              onCode:"923"
                          },
                          {
                              code:"9232",
                              level:"4",
                              name:"人民检察院",
                              node:"1",
                              onCode:"923"
                          }
                      ],
                      code:"923",
                      level:"3",
                      name:"人民法院和人民检察院",
                      node:"0",
                      onCode:"92"
                  },
                  {
                      children:[
                          {
                              code:"9291",
                              level:"4",
                              name:"消防管理机构",
                              node:"1",
                              onCode:"929"
                          },
                          {
                              code:"9299",
                              level:"4",
                              name:"其他未列明国家机构",
                              node:"1",
                              onCode:"929"
                          }
                      ],
                      code:"929",
                      level:"3",
                      name:"其他国家机构",
                      node:"0",
                      onCode:"92"
                  }
              ],
              code:"92",
              level:"2",
              name:"国家机构",
              node:"0",
              onCode:"S"
          },
          {
              children:[
                  {
                      
                      code:"931",
                      level:"3",
                      name:"人民政协",
                      node:"1",
                      onCode:"93"
                  },
                  {
                      
                      code:"932",
                      level:"3",
                      name:"民主党派",
                      node:"1",
                      onCode:"93"
                  }
              ],
              code:"93",
              level:"2",
              name:"人民政协、民主党派",
              node:"0",
              onCode:"S"
          },
          {
              children:[
                  {
                      children:[
                          {
                              code:"9411",
                              level:"4",
                              name:"基本养老保险",
                              node:"1",
                              onCode:"941"
                          },
                          {
                              code:"9412",
                              level:"4",
                              name:"基本医疗保险",
                              node:"1",
                              onCode:"941"
                          },
                          {
                              code:"9413",
                              level:"4",
                              name:"失业保险",
                              node:"1",
                              onCode:"941"
                          },
                          {
                              code:"9414",
                              level:"4",
                              name:"工伤保险",
                              node:"1",
                              onCode:"941"
                          },
                          {
                              code:"9415",
                              level:"4",
                              name:"生育保险",
                              node:"1",
                              onCode:"941"
                          },
                          {
                              code:"9419",
                              level:"4",
                              name:"其他基本保险",
                              node:"1",
                              onCode:"941"
                          }
                      ],
                      code:"941",
                      level:"3",
                      name:"基本保险",
                      node:"0",
                      onCode:"94"
                  },
                  {
                      
                      code:"942",
                      level:"3",
                      name:"补充保险",
                      node:"1",
                      onCode:"94"
                  },
                  {
                      
                      code:"949",
                      level:"3",
                      name:"其他社会保障",
                      node:"1",
                      onCode:"94"
                  }
              ],
              code:"94",
              level:"2",
              name:"社会保障",
              node:"0",
              onCode:"S"
          },
          {
              children:[
                  {
                      children:[
                          {
                              code:"9511",
                              level:"4",
                              name:"工会",
                              node:"1",
                              onCode:"951"
                          },
                          {
                              code:"9512",
                              level:"4",
                              name:"妇联",
                              node:"1",
                              onCode:"951"
                          },
                          {
                              code:"9513",
                              level:"4",
                              name:"共青团",
                              node:"1",
                              onCode:"951"
                          },
                          {
                              code:"9519",
                              level:"4",
                              name:"其他群众团体",
                              node:"1",
                              onCode:"951"
                          }
                      ],
                      code:"951",
                      level:"3",
                      name:"群众团体",
                      node:"0",
                      onCode:"95"
                  },
                  {
                      children:[
                          {
                              code:"9521",
                              level:"4",
                              name:"专业性团体",
                              node:"1",
                              onCode:"952"
                          },
                          {
                              code:"9522",
                              level:"4",
                              name:"行业性团体",
                              node:"1",
                              onCode:"952"
                          },
                          {
                              code:"9529",
                              level:"4",
                              name:"其他社会团体",
                              node:"1",
                              onCode:"952"
                          }
                      ],
                      code:"952",
                      level:"3",
                      name:"社会团体",
                      node:"0",
                      onCode:"95"
                  },
                  {
                      
                      code:"953",
                      level:"3",
                      name:"基金会",
                      node:"1",
                      onCode:"95"
                  },
                  {
                      children:[
                          {
                              code:"9541",
                              level:"4",
                              name:"宗教团体服务",
                              node:"1",
                              onCode:"954"
                          },
                          {
                              code:"9542",
                              level:"4",
                              name:"宗教活动场所服务",
                              node:"1",
                              onCode:"954"
                          }
                      ],
                      code:"954",
                      level:"3",
                      name:"宗教组织",
                      node:"0",
                      onCode:"95"
                  }
              ],
              code:"95",
              level:"2",
              name:"群众团体、社会团体和其他成员组织",
              node:"0",
              onCode:"S"
          },
          {
              children:[
                  {
                      
                      code:"961",
                      level:"3",
                      name:"社区居民自治组织",
                      node:"1",
                      onCode:"96"
                  },
                  {
                      
                      code:"962",
                      level:"3",
                      name:"村民自治组织",
                      node:"1",
                      onCode:"96"
                  }
              ],
              code:"96",
              level:"2",
              name:"基层群众自治组织及其他组织",
              node:"0",
              onCode:"S"
          }
      ],
      code:"S",
      level:"1",
      name:"公共管理、社会保障和社会组织",
      node:"0",
      
  },
  {
      code:"T",
      level:"1",
      name:"国际组织",
      node:"1",
      
  }
];

export {institutionTypeData}
